Update paper.bib
rmsare/pymccrgb pull request #21
Opened 2019-10-30 14:08 UTC by arfon

Fixing comma

2019-10-30 14:34 UTC, kthyng requested changes
@arfon still need to remove comma from line above yes?

2019-10-30 14:34 UTC, kthyng commented on paper/paper.bib
>    year={2011},
extra comma here. Not sure how I can just delete it though.

2019-10-30 14:39 UTC, arfon commented on paper/paper.bib
>    year={2011},
No, that one is OK.

2019-10-30 14:39 UTC, arfon commented
Just to confirm, this PR _as is_ will work fine.

2019-10-31 03:26 UTC, merged

2019-10-31 03:26 UTC, rmsare commented
Thanks for catching this, and sorry for the delay on my end.